dotenv: ../../scripts/.env
cronos_777-1:
  cmd: cronosd
  start-flags: "--trace --unsafe-experimental"
  app-config:
    index-events:
      - ethereum_tx.ethereumTxHash
    json-rpc:
      address: "0.0.0.0:{EVMRPC_PORT}"
      ws-address: "0.0.0.0:{EVMRPC_PORT_WS}"
  validators:
    - coins: 1000000000000000000stake,10000000000000000000000basetcro
      staked: 1000000000000000000stake
      mnemonic: ${VALIDATOR1_MNEMONIC}
    - coins: 1000000000000000000stake,10000000000000000000000basetcro
      staked: 1000000000000000000stake
      mnemonic: ${VALIDATOR2_MNEMONIC}
  accounts:
    - name: community
      coins: 10000000000000000000000basetcro
      mnemonic: ${COMMUNITY_MNEMONIC}
  genesis:
    app_state:
      evm:
        params:
          evm_denom: basetcro
      cronos:
        params:
          cronos_admin: crc12luku6uxehhak02py4rcz65zu0swh7wjsrw0pp
          enable_auto_deployment: false
      gov:
        voting_params:
          voting_period: "10s"
        deposit_params:
          max_deposit_period: "10s"
          min_deposit:
            - denom: "basetcro"
              amount: "1"
      feemarket:
        params:
          no_base_fee: false
          initial_base_fee: 100000000000
